server.port=8080

spring.application.name=Shurlty

# --- PostgreSQL Database Configuration ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate Settings ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- JWT Settings ---
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiry-seconds=${APP_JWT_EXPIRY_SECONDS:3600}
